# ============================================================
#  Host Variables - AC-1
# ============================================================
hostname: "AC-1"
snmp_chassis_id: "AC-1"
mgmt_ip: "192.168.99.11"

uplink_interfaces:
  - interface: "Ethernet0/0"
    description: "Trunk to CORE-1 e1/0"
  - interface: "Ethernet0/1"
    description: "Trunk to CORE-2 e1/0 (cross)"

downlink_interfaces:
  - interface: "Ethernet1/0"
    description: "Access to PC1"
    vlan: 10

# Bảo vệ cổng đang cắm Ansible server / jump host để tránh đổi VLAN gây mất SSH.
protected_mgmt_interfaces:
  - "Ethernet1/0"
