# ============================================================
#  Host Variables - AC-2
# ============================================================
hostname: "AC-2"
snmp_chassis_id: "AC-2"
mgmt_ip: "192.168.99.12"

uplink_interfaces:
  - interface: "Ethernet0/0"
    description: "Trunk to CORE-1 e1/1"
  - interface: "Ethernet0/1"
    description: "Trunk to CORE-2 e1/1 (cross)"

downlink_interfaces:
  - interface: "Ethernet1/0"
    description: "Access to PC2"
    vlan: 10
