---
- name: "BASE | Kiểm tra biến đầu vào"
  ansible.builtin.import_tasks: validate.yml

- name: "BASE | Chuẩn hóa system"
  ansible.builtin.import_tasks: system.yml

- name: "BASE | Cấu hình Static Routes"
  ansible.builtin.import_tasks: routing.yml

- name: "BASE | Chuẩn hóa local users"
  ansible.builtin.import_tasks: users.yml

- name: "BASE | Chuẩn hóa SSH và line access"
  ansible.builtin.import_tasks: access.yml

- name: "BASE | Lưu cấu hình khi có thay đổi"
  ansible.builtin.import_tasks: save.yml
