# ============================================================
#  Ansible Inventory - Network Automation Lab
# ============================================================

[routers]
Router ansible_host=192.168.9.99

[core]
CORE-1 ansible_host=192.168.99.2
CORE-2 ansible_host=192.168.99.3

[access]
AC-1 ansible_host=192.168.99.11
AC-2 ansible_host=192.168.99.12
AC-3 ansible_host=192.168.99.13
AC-4 ansible_host=192.168.99.14
AC-5 ansible_host=192.168.99.15

# -------------------------
# Group cha
# -------------------------
[network:children]
routers
core
access

[switches:children]
core
access

# -------------------------
# GLOBAL VARIABLES
# -------------------------
[network:vars]

# ===== Ansible connection cho network devices =====
ansible_connection=ansible.netcommon.network_cli
ansible_network_os=cisco.ios.ios

# ===== Privilege mode (enable) =====
ansible_become=true
ansible_become_method=enable

# ===== Python interpreter fix =====
ansible_python_interpreter=/usr/bin/python3

# ===== SSH stability =====
ansible_command_timeout=60
ansible_connect_timeout=30

# ===== Disable SSH prompt issues =====
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'