# ============================================================
#  Ansible Inventory - Network Lab
#  Phân nhóm: routers, core, access
# ============================================================

[routers]
Router  ansible_host=192.168.9.99

[core]
CORE-1  ansible_host=192.168.99.2
CORE-2  ansible_host=192.168.99.3

[access]
AC-1    ansible_host=192.168.99.11
AC-2    ansible_host=192.168.99.12
AC-3    ansible_host=192.168.99.13
AC-4    ansible_host=192.168.99.14
AC-5    ansible_host=192.168.99.15

# --- Nhóm cha chứa tất cả thiết bị mạng ---
[network:children]
routers
core
access

# --- Nhóm switches (Core + Access) ---
[switches:children]
core
access
